version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: catalog-management-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog-management-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
